---
- hosts: localhost
  gather_facts: no
  vars:
    namespace: 'mine'
  tasks:
    - name: Write new value to secret store
      hashivault_write:
        secret: '{{namespace}}/name'
        data:
            value: 'one'
      register: 'vault_write'
    - assert:
        that:
          - "{{vault_write.changed}} == True"
          - "'{{vault_write.msg}}' == 'Secret secret/{{namespace}}/name written'"

    - name: Overwrite value to secret store
      hashivault_write:
        secret: '{{namespace}}/name'
        data:
            value: 'two'
      register: 'vault_write'
    - assert:
        that:
          - "{{vault_write.changed}} == True"
          - "'{{vault_write.msg}}' == 'Secret secret/{{namespace}}/name written'"

    - name: Overwrite same value to secret store
      hashivault_write:
        secret: '{{namespace}}/name'
        data:
            value: 'two'
      register: 'vault_write'
    - assert: { that: "{{vault_write.changed}} == True" }

    - name: Delete own secret
      hashivault_delete:
        secret: '{{namespace}}/owl'

    - name: Update brand new value
      hashivault_write:
        secret: '{{namespace}}/owl'
        update: True
        data:
            type: 'great horned'
      register: 'vault_write'
    - assert:
        that:
          - "{{vault_write.changed}} == True"
          - "'{{vault_write.msg}}' == 'Secret secret/{{namespace}}/owl written'"

    - name: Update value to secret store
      hashivault_write:
        secret: '{{namespace}}/name'
        update: True
        data:
            value: 'three'
      register: 'vault_write'
    - assert:
        that:
          - "{{vault_write.changed}} == True"
          - "'{{vault_write.msg}}' == 'Secret secret/{{namespace}}/name written'"

    - name: Update same value to secret store
      hashivault_write:
        secret: '{{namespace}}/name'
        update: True
        data:
            value: 'three'
      register: 'vault_write'
    - assert: { that: "{{vault_write.changed}} == False" }

    - name: Update some other value to secret store
      hashivault_write:
        secret: '{{namespace}}/name'
        update: True
        data:
            other_value: 'four'
      register: 'vault_write'
    - assert: { that: "{{vault_write.changed}} == True" }

    - name: Read the secret value
      hashivault_read:
        secret: '{{namespace}}/name'
        key: 'value'
      register: 'vault_read'
    - assert: { that: "'{{vault_read.value}}' == 'three'" }

    - name: Read other secret value
      hashivault_read:
        secret: '{{namespace}}/name'
        key: 'other_value'
      register: 'vault_read'
    - assert: { that: "'{{vault_read.value}}' == 'four'" }

    - set_fact:
        looky_secret: "{{lookup('hashivault', '{{namespace}}/name', 'value')}}"
    - assert: { that: "'{{looky_secret}}' == 'three'" }

    - set_fact:
        owl_type: "{{lookup('hashivault', '{{namespace}}/owl', 'type')}}"
    - assert: { that: "'{{owl_type}}' == 'great horned'" }

    - name: Delete a secret
      hashivault_delete:
        secret: '{{namespace}}/name'
      register: 'vault_secret_delete'
    - assert: { that: "{{vault_secret_delete.changed}} == True" }
    - assert: { that: "{{vault_secret_delete.rc}} == 0" }
    - assert: { that: "'{{vault_secret_delete.msg}}' == 'Secret secret/{{namespace}}/name deleted'" }

    - name: Make sure secret value is gone
      hashivault_read:
        secret: '{{namespace}}/name'
      register: 'vault_read'
      failed_when: False
    - assert: { that: "{{vault_read.changed}} == False" }
    - assert: { that: "'{{vault_read.msg}}' == 'Secret {{namespace}}/name is not in vault'" }
