---
- hosts: localhost
  gather_facts: no
  tasks:
    - hashivault_init:
      register: 'vault_init'
    - block:
      - name: "Vault not initialized - Check exit code"
        assert: { that: "{{vault_init.rc}} == 0" }
      when: "vault_init.changed == False"
    - block:
      - name: "Vault initialized - Check exit code"
        assert: { that: "{{vault_init.rc}} == 0" }
      - name: "Check that keys and root token are defined"
        assert:
          that:
            - "vault_init.keys is defined"
            - "vault_init.root_token is defined"
      when: "vault_init.changed == True"
