---
- hosts: localhost
  gather_facts: no
  vars:
    namespace: 'fourofour'
  tasks:
    - set_fact:
        looky_secret: "{{lookup('hashivault', '{{namespace}}/nothome', 'value', default='headrest')}}"
    - assert: { that: "'{{looky_secret}}' == 'headrest'" }

    - name: Read nonexistent secret value ignoring error
      hashivault_read:
        secret: '{{namespace}}/nothome'
        key: 'value'
      register: 'vault_read'
      failed_when: False
    - assert: { that: "{{vault_read.failed}} == False" }
    - assert: { that: "{{vault_read.rc}} == 1" }
    - assert: { that: "'{{vault_read.msg}}' == 'Secret fourofour/nothome is not in vault'" }

    - name: Read nonexistent secret value with default
      hashivault_read:
        secret: '{{namespace}}/nothome'
        key: 'value'
        default: ''
      register: 'vault_read'
    - assert: { that: "'{{vault_read.value}}' == ''" }
    - assert: { that: "{{vault_read.failed}} == False" }
    - assert: { that: "{{vault_read.rc}} == 0" }

    - name: Read nonexistent secret value with something defaulted
      hashivault_read:
        secret: '{{namespace}}/nothome'
        key: 'value'
        default: 'carseat'
      register: 'vault_read'
    - assert: { that: "'{{vault_read.value}}' == 'carseat'" }