---
- hosts: localhost
  gather_facts: no
  vars:
    dict_value:
      foo: 'bar'
      baz: 'stuff'
    array_value:
      - 'one'
      - 'two'
      - 'three'
  tasks:
    - hashivault_delete:
        secret: 'basic'
    - hashivault_delete:
        secret: stalks/bean
    - name: Write verify it succeeds
      hashivault_write:
        secret: basic
        data:
            foo: 'foe'
            fie: 'fum'
      register: vault_write
    - assert: { that: "{{vault_write.changed}} == True" }
    - assert: { that: "'{{vault_write.msg}}' == 'Secret secret/basic written'" }
    - assert: { that: "{{vault_write.rc}} == 0" }

    - name: Write again no update verify changed
      hashivault_write:
        secret: basic
        data:
          foo: 'foe'
          fie: 'fum'
      register: vault_write
    - assert: { that: "{{vault_write.changed}} == True" }
    - assert: { that: "'{{vault_write.msg}}' == 'Secret secret/basic written'" }
    - assert: { that: "{{vault_write.rc}} == 0" }

    - name: Update again and verify no change
      hashivault_write:
        update: True
        secret: basic
        data:
          foo: 'foe'
          fie: 'fum'
      register: vault_write
    - assert: { that: "{{vault_write.changed}} == False" }
    - assert: { that: "{{vault_write.rc}} == 0" }

    - name: Update new value and detect change
      hashivault_write:
        update: True
        secret: basic
        data:
          foo: 'new'
          fie: 'fum'
      register: vault_write
    - assert: { that: "{{vault_write.changed}} == True" }
    - assert: { that: "'{{vault_write.msg}}' == 'Secret secret/basic written'" }
    - assert: { that: "{{vault_write.rc}} == 0" }

    - name: Update a brand new secret in folder
      hashivault_write:
        update: True
        secret: stalks/bean
        data:
          height: tall
      register: vault_write
    - assert: { that: "{{vault_write.changed}} == True" }
    - assert: { that: "'{{vault_write.msg}}' == 'Secret secret/stalks/bean written'" }
    - assert: { that: "{{vault_write.rc}} == 0" }

    - name: Write secret dictionary
      hashivault_write:
        secret: basic_dict
        data: "{{ dict_value }}"
    - assert: { that: "{{vault_write.changed}} == True" }
    - assert: { that: "{{vault_write.rc}} == 0" }

    - name: Write array type secret
      hashivault_write:
        secret: basic_array
        data:
            value: "{{array_value}}"
