---

- hosts: localhost
  gather_facts: no
  vars:
    address: consul.local:8500
    scheme: https
    consul_token: myAwesomeConsulManagementToken
    role_name: test
    policy: a2V5ICIvZm9vL2JhciIgeyBwb2xpY3kgPSAicmVhZCIgfQ==
  tasks:
    - name: enable consul secret engine
      hashivault_secret_enable:
        name: consul
        backend: consul
         
    - name: successfully configure
      hashivault_consul_secret_engine_config:
        address: "{{ address }}"
        scheme: "{{ scheme }}"
        consul_token: "{{ consul_token }}"

    - name: fail write a role
      hashivault_consul_secret_engine_role:
        name: "{{ role_name }}"
      register: fail_write
      failed_when: false

    - assert: { that: "{{ fail_write.changed }} == False" }

    - name: successfully write a role
      hashivault_consul_secret_engine_role:
        name: "{{ role_name }}"
        policy: "{{ policy }}"
      register: success_write
    
    - assert: { that: "{{ success_write.changed }} == True" }

    - name: skip write a role
      hashivault_consul_secret_engine_role:
        name: "{{ role_name }}"
        policy: "{{ policy }}"
      register: idem_write
    
    - assert: { that: "{{ idem_write.changed }} == False" }

    - name: delete role
      hashivault_consul_secret_engine_role:
        name: "{{ role_name }}"
        state: absent
      register: success_del
    
    - assert: { that: "{{ success_del.changed }} == True" }

    - name: skip delete role
      hashivault_consul_secret_engine_role:
        name: "{{ role_name }}"
        state: absent
      register: success_del
    
    - assert: { that: "{{ success_del.changed }} == False" }
