---
- hosts: localhost
  tasks:
    - hashivault_init:
      register: 'vault_init'
    - block:
      - assert: { that: "{{vault_init.rc}} == 0" }
      when: "vault_init.changed == False"
    - block:
      - assert: { that: "'keys' in {{vault_init}}" }
      - assert: { that: "'root_token' in {{vault_init}}" }
      - assert: { that: "{{vault_init.rc}} == 0" }
      when: "vault_init.changed == True"
