---
- include: test_status.yml

- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Unseal vault"
      hashivault_unseal:
        keys: '{{vault_keys}}'
      register: 'vault_unseal'

    - name: "Check that vault is now unsealed"
      assert:
        that:
          - "{{vault_unseal.changed}} == True"
          - "{{vault_unseal.status.progress}} == 0"
          - "{{vault_unseal.status.sealed}} == False"
          - "{{vault_unseal.rc}} == 0"
