---
- hosts: localhost
  tasks:
    - hashivault_secret_list:
      register: 'vault_secret_list'
    - hashivault_secret_disable:
        name: "ephemeral"
    - hashivault_secret_enable:
        name: "ephemeral"
        backend: "generic"
      register: 'vault_secret_enable'
    - assert: { that: "{{vault_secret_enable.changed}} == True" }
    - assert: { that: "{{vault_secret_enable.rc}} == 0" }
    - hashivault_secret_disable:
        name: "ephemeral"
      register: 'vault_secret_disable'
    - assert: { that: "{{vault_secret_enable.changed}} == True" }
    - assert: { that: "{{vault_secret_enable.rc}} == 0" }
