---
- hosts: localhost
  gather_facts: no
  vars:
    foo_value: 'foe'
    fie_value: 'fum'
    dict_value:
      foo: 'bar'
      baz: 'stuff'
  tasks:
    - name: Write basic secret and verify it is changed
      hashivault_write:
        secret: 'giant'
        data:
          foo: '{{foo_value}}'
          fie: '{{fie_value}}'
      register: 'vault_write'
    - assert: { that: vault_write.changed == True }
    - assert: { that: vault_write.rc == 0 }

    - name: Write single secret in folder 
      hashivault_write:
        secret: stalks/bean
        data:
          height: tall
      register: vault_write
    - assert: { that: vault_write.changed == True }
    - assert: { that: vault_write.rc == 0 }

    - name: Write secret dictionary
      hashivault_write:
        secret: 'some_dict'
        data: "{{ dict_value }}"
      register: vault_write
    - assert: { that: vault_write.changed == True }
    - assert: { that: vault_write.rc == 0 }
