---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: List secret stores
      hashivault_secret_list:
      register: 'vault_secret_list'
    - name: Make sure ephemeral secret store is disabled
      hashivault_secret_disable:
        name: "ephemeral"
      failed_when: False
    - name: Enable ephermal secret store
      hashivault_secret_enable:
        name: "ephemeral"
        backend: "generic"
      register: 'vault_secret_enable'
    - assert: { that: "{{vault_secret_enable.changed}} == True" }
    - assert: { that: "{{vault_secret_enable.rc}} == 0" }

    - name: Write a value to the ephermal store
      hashivault_write:
        secret: '/ephemeral/name'
        data:
            value: 'ephemeral_stuff'

    - hashivault_write:
        secret: 'name'
        data:
            value: 'secret_stuff'

    - hashivault_read:
        secret: 'name'
        key: 'value'
      register: 'vault_read'
    - assert: { that: "'{{vault_read.value}}' == 'secret_stuff'" }

    - name: Read a value from the ephemeral secret store
      hashivault_read:
        secret: '/ephemeral/name'
        key: 'value'
      register: 'vault_read'
    - assert: { that: "'{{vault_read.value}}' == 'ephemeral_stuff'" }

    - set_fact:
        looky_secret: "{{lookup('hashivault', 'name', 'value')}}"
    - assert: { that: "'{{looky_secret}}' == 'secret_stuff'" }

    - set_fact:
        looky_ephemeral: "{{lookup('hashivault', '/ephemeral/name', 'value')}}"
    - assert: { that: "'{{looky_ephemeral}}' == 'ephemeral_stuff'" }

    - name: Disable ephermeral secret store
      hashivault_secret_disable:
        name: "ephemeral"
      register: 'vault_secret_disable'
    - assert: { that: "{{vault_secret_enable.changed}} == True" }
    - assert: { that: "{{vault_secret_enable.rc}} == 0" }
