---
- hosts: localhost
  gather_facts: no
  vars:
    dict_value:
      foo: 'bar'
      baz: 'stuff'
  tasks:
    - name: Write secret dictionary
      hashivault_write:
        secret: 'some_dict'
        data: "{{ dict_value }}"

    - name: Read secret dictionary
      hashivault_read:
        secret: 'some_dict'
      register: 'vault_read_dict'
    - assert: { that: "vault_read_dict.value == dict_value" }
    - assert: { that: "{{vault_read_dict.rc}} == 0" }
