---
- hosts: localhost
  vars:
    name: 'terry'
    rules: >
        path "secret/{{name}}/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
        } 
        path "secret/{{name}}" {
          capabilities = ["list"]
        } 
    expected: "{{rules | regex_replace('\n', '')}}"
  tasks:
    - hashivault_policy_set:
        name: "{{name}}"
        rules: "{{rules}}"
      register: 'vault_policy_set'
    - assert: { that: "{{vault_policy_set.changed}} == True" }
    - assert: { that: "{{vault_policy_set.rc}} == 0" }

    - hashivault_policy_get:
        name: '{{name}}'
      register: 'vault_policy_get'
    - assert: { that: "{{vault_policy_get.changed}} == False" }
    - set_fact:
        actual: "{{vault_policy_get.rules | regex_replace('\n', '')}}"
    - assert: { that: "'{{expected}}' == '{{actual}}'" }
    - assert: { that: "{{vault_policy_get.rc}} == 0" }

    - hashivault_policy_list:
      register: 'vault_policy_list'
    - assert: { that: "{{vault_policy_list.changed}} == False" }
    - fail: msg="policy {{name}} not in list"
      when: name not in vault_policy_list.policies
    - assert: { that: "{{vault_policy_list.rc}} == 0" }

    - hashivault_policy_delete:
        name: '{{name}}'
      register: 'vault_policy_delete'
    - assert: { that: "{{vault_policy_delete.changed}} == True" }
    - assert: { that: "{{vault_policy_delete.rc}} == 0" }

    - hashivault_policy_list:
      register: 'vault_policy_list'
    - assert: { that: "{{vault_policy_list.changed}} == False" }
    - fail: msg="policy {{name}} in list"
      when: name in vault_policy_list.policies
    - assert: { that: "{{vault_policy_list.rc}} == 0" }
